// Real MCPs from OMA-AI marketplace — Vercel primary data source
// Supabase used when available (local dev / server-side)
// This ensures the marketplace always works, even without DB connectivity

export interface MCPServer {
  id: string;
  name: string;
  slug: string;
  description: string;
  long_description?: string;
  category: string;
  pricing_usdc: number;
  x402_enabled: boolean;
  verified: boolean;
  author: string;
  version: string;
  mcp_endpoint: string;
  documentation_url?: string;
  repository?: string;
  tools_count: number;
  rating: number;
  calls: number;
  tags: string[];
}

export const MARKETPLACE_MCPS: MCPServer[] = [
  {
    id: '1a3b7c42-2047-4184-b590-ba27649a4c7c',
    name: 'Jupiter Swap MCP',
    slug: 'jupiter-swap-mcp',
    description: 'Solana DEX aggregator. Best rates across Raydium, Orca, Marinade, Jupiter.',
    category: 'Finance & Crypto',
    pricing_usdc: 0.002,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/jupiter-swap-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/jupiter',
    repository: 'https://github.com/oma-ai/jupiter-mcp',
    tools_count: 4,
    rating: 4.8,
    calls: 12847,
    tags: ['solana', 'dex', 'swap', 'trading', 'defi'],
  },
  {
    id: '2b4d8e53-3158-5295-c601-cb38750b5d68',
    name: 'Helius MCP',
    slug: 'helius-mcp',
    description: 'Full Solana RPC suite — getBlock, getSignaturesForAddress, DAS API, webhooks.',
    category: 'Infrastructure',
    pricing_usdc: 0.001,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.2.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/helius-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/helius',
    repository: 'https://github.com/oma-ai/helius-mcp',
    tools_count: 63,
    rating: 4.9,
    calls: 34521,
    tags: ['solana', 'rpc', 'infrastructure', 'development'],
  },
  {
    id: '3c5e9f64-4269-6306-d712-dc49861c6e79',
    name: 'pump.fun Sniper MCP',
    slug: 'pumpfun-sniper',
    description: 'Score pump.fun tokens before buying. Dev wallet analysis, RugCheck, honeypot detection.',
    category: 'Finance & Crypto',
    pricing_usdc: 0.005,
    x402_enabled: true,
    verified: true,
    author: 'FrankieMolt',
    version: '2.1.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/pumpfun-sniper',
    documentation_url: 'https://docs.oma-ai.com/mcps/pumpfun',
    repository: 'https://github.com/FrankieMolt/pumpfun-sniper',
    tools_count: 5,
    rating: 4.7,
    calls: 8932,
    tags: ['solana', 'meme', 'pumpfun', 'snipe', 'trading'],
  },
  {
    id: '4d6f0a75-5370-7417-e823-ed50972d7f80',
    name: 'TradeRouter MCP',
    slug: 'trade-router',
    description: 'MEV-protected Jupiter swaps, trailing orders, DCA, and limit orders on Solana.',
    category: 'Finance & Crypto',
    pricing_usdc: 0.003,
    x402_enabled: true,
    verified: true,
    author: 'FrankieMolt',
    version: '1.5.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/trade-router',
    documentation_url: 'https://docs.oma-ai.com/mcps/traderouter',
    repository: 'https://github.com/FrankieMolt/trade-router',
    tools_count: 8,
    rating: 4.6,
    calls: 5621,
    tags: ['solana', 'mev', 'swap', 'trading', 'dca'],
  },
  {
    id: '5e7a1b86-6481-8529-f934-fe61083e8g91',
    name: 'Vercel MCP',
    slug: 'vercel-mcp',
    description: 'Deploy, manage, and monitor Vercel projects. Env vars, builds, rollbacks.',
    category: 'Development',
    pricing_usdc: 0.001,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/vercel-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/vercel',
    tools_count: 150,
    rating: 4.7,
    calls: 22105,
    tags: ['vercel', 'deployment', 'devops', 'hosting'],
  },
  {
    id: '6f8b2c97-7592-9630-a045-ff72194f9h02',
    name: 'Coolify MCP',
    slug: 'coolify-mcp',
    description: 'Self-host databases, Redis, Docker containers. Full Coolify API via MCP.',
    category: 'Infrastructure',
    pricing_usdc: 0.001,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/coolify-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/coolify',
    tools_count: 38,
    rating: 4.5,
    calls: 9803,
    tags: ['self-host', 'coolify', 'database', 'docker', 'infrastructure'],
  },
  {
    id: '7g9c3d08-8603-a741-b156-ag83205i0j13',
    name: 'GitHub MCP',
    slug: 'github-mcp',
    description: 'Code, PRs, issues, workflows. Full GitHub API for AI agents.',
    category: 'Development',
    pricing_usdc: 0,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/github-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/github',
    tools_count: 26,
    rating: 4.8,
    calls: 31240,
    tags: ['github', 'code', 'pr', 'ci', 'development'],
  },
  {
    id: '8h0d4e19-9714-b852-c267-bh94316j1k24',
    name: 'Anthropic Claude MCP',
    slug: 'anthropic-claude-mcp',
    description: 'Claude 3.5/3.7 Sonnet with vision, structured outputs, extended thinking.',
    category: 'AI & ML',
    pricing_usdc: 0.01,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/anthropic-claude-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/claude',
    tools_count: 12,
    rating: 4.9,
    calls: 45678,
    tags: ['ai', 'claude', 'anthropic', 'llm', 'vision'],
  },
  {
    id: '9i1e5f20-a825-c963-d378-ci05427k2l35',
    name: 'Browser Automation MCP',
    slug: 'browser-automation-mcp',
    description: 'Headless Chrome control — navigate, click, type, screenshot via MCP.',
    category: 'Automation',
    pricing_usdc: 0.002,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/browser-automation-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/browser',
    tools_count: 29,
    rating: 4.6,
    calls: 18934,
    tags: ['browser', 'automation', 'chrome', 'scraping'],
  },
  {
    id: '10j2f6g31-b936-da74-e489-dj16538l3m46',
    name: 'PostgreSQL MCP',
    slug: 'postgresql-mcp',
    description: 'Query, insert, update PostgreSQL. AI agents can talk directly to databases.',
    category: 'Data',
    pricing_usdc: 0,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/postgresql-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/postgresql',
    tools_count: 8,
    rating: 4.7,
    calls: 14230,
    tags: ['postgresql', 'database', 'sql', 'data'],
  },
  {
    id: '11k3g7h42-c047-eb85-f590-ek27649m4n57',
    name: 'OpenAI GPT MCP',
    slug: 'openai-gpt-mcp',
    description: 'GPT-4o, o1, o3-mini via MCP. Structured outputs, vision, function calling.',
    category: 'AI & ML',
    pricing_usdc: 0.015,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/openai-gpt-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/openai',
    tools_count: 10,
    rating: 4.8,
    calls: 38920,
    tags: ['ai', 'openai', 'gpt', 'llm'],
  },
  {
    id: '12l4h8i53-d158-fc96-ag601-el38750n5o68',
    name: 'Figma MCP',
    slug: 'figma-mcp',
    description: 'Read Figma files, extract components, styles, and export assets via MCP.',
    category: 'Design',
    pricing_usdc: 0.002,
    x402_enabled: true,
    verified: false,
    author: 'Community',
    version: '0.9.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/figma-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/figma',
    tools_count: 7,
    rating: 4.4,
    calls: 7234,
    tags: ['figma', 'design', 'ui', 'components'],
  },
  {
    id: '13m5i9j64-e269-ga07-bh712-fm49861o6p79',
    name: 'Fetch MCP',
    slug: 'fetch-mcp',
    description: 'Web fetch — HTML, Markdown, JSON, YouTube transcripts. AI agents read the web.',
    category: 'Research',
    pricing_usdc: 0,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/fetch-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/fetch',
    tools_count: 6,
    rating: 4.8,
    calls: 27890,
    tags: ['fetch', 'web', 'research', 'scraping', 'youtube'],
  },
  {
    id: '14n6j0k75-f370-hb18-ci823-gn50972p7q80',
    name: 'Docker MCP',
    slug: 'docker-mcp',
    description: 'Manage Docker containers, images, volumes, networks via MCP.',
    category: 'Infrastructure',
    pricing_usdc: 0,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/docker-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/docker',
    tools_count: 1,
    rating: 4.5,
    calls: 11234,
    tags: ['docker', 'containers', 'infrastructure', 'devops'],
  },
  {
    id: '15o7k1l86-g481-ic29-dj934-ho61083q8r91',
    name: 'Exa Search MCP',
    slug: 'exa-search-mcp',
    description: 'AI-powered web search. Natural language queries, full-text extraction, citations.',
    category: 'Research',
    pricing_usdc: 0.001,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/exa-search-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/exa',
    tools_count: 3,
    rating: 4.7,
    calls: 19340,
    tags: ['search', 'research', 'ai', 'web'],
  },
  {
    id: '16p8l2m97-h592-jd30-ek045-ip72194r9s02',
    name: 'Email MCP',
    slug: 'email-mcp',
    description: 'Send transactional emails via SMTP, SES, or Resend. AI agents notify users.',
    category: 'Communication',
    pricing_usdc: 0.0005,
    x402_enabled: true,
    verified: false,
    author: 'Community',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/email-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/email',
    tools_count: 11,
    rating: 4.3,
    calls: 5432,
    tags: ['email', 'notifications', 'communication'],
  },
  {
    id: '17q9m3n08-i603-ke41-fl156-jq83205s0t13',
    name: 'Cohere Command MCP',
    slug: 'cohere-command-mcp',
    description: 'Cohere Command R/R+ for AI agents. 200k context, reranking, embeddings.',
    category: 'AI & ML',
    pricing_usdc: 0.008,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/cohere-command-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/cohere',
    tools_count: 8,
    rating: 4.6,
    calls: 14560,
    tags: ['ai', 'cohere', 'llm', 'reasoning'],
  },
  {
    id: '18r0n4o19-j714-lf52-gm267-kr94316t1u24',
    name: 'Stable Diffusion MCP',
    slug: 'stable-diffusion-mcp',
    description: 'Image generation via Stable Diffusion 3, Flux, ComfyUI. Inpaint, outpaint.',
    category: 'AI & ML',
    pricing_usdc: 0.01,
    x402_enabled: true,
    verified: false,
    author: 'Community',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/stable-diffusion-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/stable-diffusion',
    tools_count: 6,
    rating: 4.5,
    calls: 9876,
    tags: ['image', 'generation', 'ai', 'stable-diffusion'],
  },
  {
    id: '19s1o5p20-k825-mg63-hn378-ls05427u2v35',
    name: 'SearXNG MCP',
    slug: 'searxng-mcp',
    description: 'Private, bias-free web search. 100+ engines, no tracking, no ads.',
    category: 'Research',
    pricing_usdc: 0,
    x402_enabled: true,
    verified: true,
    author: 'OMA-AI Team',
    version: '1.0.0',
    mcp_endpoint: 'https://www.oma-ai.com/mcp/searxng-mcp',
    documentation_url: 'https://docs.oma-ai.com/mcps/searxng',
    tools_count: 2,
    rating: 4.9,
    calls: 42105,
    tags: ['search', 'privacy', 'research', 'searxng'],
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'All', count: 19 },
  { id: 'finance-crypto', name: 'Finance & Crypto', count: 4 },
  { id: 'ai-ml', name: 'AI & ML', count: 4 },
  { id: 'development', name: 'Development', count: 2 },
  { id: 'infrastructure', name: 'Infrastructure', count: 3 },
  { id: 'research', name: 'Research', count: 3 },
  { id: 'automation', name: 'Automation', count: 1 },
  { id: 'data', name: 'Data', count: 1 },
  { id: 'design', name: 'Design', count: 1 },
  { id: 'communication', name: 'Communication', count: 1 },
];
